create table car (
	id BIGSERIAL NOT NULL PRIMARY KEY,
	model VARCHAR(50) NOT NULL,
	make VARCHAR(50) NOT NULL,
	year VARCHAR(50) NOT NULL
);
insert into car (id, model, make, year) values (1, 'Grand Caravan', 'Dodge', 2012);
insert into car (id, model, make, year) values (2, 'Passat', 'Volkswagen', 2008);
insert into car (id, model, make, year) values (3, 'Sidekick', 'Suzuki', 1996);
insert into car (id, model, make, year) values (4, 'Countach', 'Lamborghini', 1986);
insert into car (id, model, make, year) values (5, 'E-Class', 'Mercedes-Benz', 1984);
insert into car (id, model, make, year) values (6, 'Sequoia', 'Toyota', 2010);
insert into car (id, model, make, year) values (7, 'Explorer', 'Ford', 1991);
insert into car (id, model, make, year) values (8, 'Galant', 'Mitsubishi', 2008);
insert into car (id, model, make, year) values (9, 'Rio', 'Kia', 2003);
insert into car (id, model, make, year) values (10, 'Blazer', 'Chevrolet', 1997);
insert into car (id, model, make, year) values (11, 'Cherokee', 'Jeep', 1995);
insert into car (id, model, make, year) values (12, 'Corvette', 'Chevrolet', 1965);
insert into car (id, model, make, year) values (13, 'Land Cruiser', 'Toyota', 2013);
insert into car (id, model, make, year) values (14, 'XK', 'Jaguar', 2008);
insert into car (id, model, make, year) values (15, '5 Series', 'BMW', 2004);
insert into car (id, model, make, year) values (16, 'Galant', 'Mitsubishi', 2011);
insert into car (id, model, make, year) values (17, 'Grand Cherokee', 'Jeep', 1994);
insert into car (id, model, make, year) values (18, '6 Series', 'BMW', 1989);
insert into car (id, model, make, year) values (19, 'Club Wagon', 'Ford', 1994);
insert into car (id, model, make, year) values (20, 'Galant', 'Mitsubishi', 1999);
insert into car (id, model, make, year) values (21, 'CL-Class', 'Mercedes-Benz', 2000);
insert into car (id, model, make, year) values (22, 'Challenger', 'Mitsubishi', 2003);
insert into car (id, model, make, year) values (23, 'Forester', 'Subaru', 2010);
insert into car (id, model, make, year) values (24, 'Sentra', 'Nissan', 2003);
insert into car (id, model, make, year) values (25, 'Pathfinder', 'Nissan', 2006);
insert into car (id, model, make, year) values (26, 'MR2', 'Toyota', 1992);
insert into car (id, model, make, year) values (27, 'Eldorado', 'Cadillac', 1998);
insert into car (id, model, make, year) values (28, 'Avalanche 2500', 'Chevrolet', 2002);
insert into car (id, model, make, year) values (29, '3500', 'GMC', 1997);
insert into car (id, model, make, year) values (30, '458 Italia', 'Ferrari', 2011);
insert into car (id, model, make, year) values (31, 'Sentra', 'Nissan', 2008);
insert into car (id, model, make, year) values (32, 'Range Rover', 'Land Rover', 1993);
insert into car (id, model, make, year) values (33, 'Tempo', 'Ford', 1988);
insert into car (id, model, make, year) values (34, 'Suburban 2500', 'Chevrolet', 2001);
insert into car (id, model, make, year) values (35, 'Torrent', 'Pontiac', 2008);
insert into car (id, model, make, year) values (36, 'CR-Z', 'Honda', 2012);
insert into car (id, model, make, year) values (37, 'CL-Class', 'Mercedes-Benz', 1999);
insert into car (id, model, make, year) values (38, 'Montero Sport', 'Mitsubishi', 2001);
insert into car (id, model, make, year) values (39, 'Savana 2500', 'GMC', 2011);
insert into car (id, model, make, year) values (40, '2500', 'GMC', 1997);
insert into car (id, model, make, year) values (41, 'Roadmaster', 'Buick', 1994);
insert into car (id, model, make, year) values (42, 'Cougar', 'Mercury', 1995);
insert into car (id, model, make, year) values (43, 'Civic', 'Honda', 2008);
insert into car (id, model, make, year) values (44, 'M3', 'BMW', 2006);
insert into car (id, model, make, year) values (45, 'Rio', 'Kia', 2013);
insert into car (id, model, make, year) values (46, 'Vantage', 'Aston Martin', 2008);
insert into car (id, model, make, year) values (47, 'Rio', 'Kia', 2009);
insert into car (id, model, make, year) values (48, 'Venture', 'Chevrolet', 2001);
insert into car (id, model, make, year) values (49, 'GX', 'Lexus', 2009);
insert into car (id, model, make, year) values (50, 'Freelander', 'Land Rover', 2010);
insert into car (id, model, make, year) values (51, 'MX-6', 'Mazda', 1995);
insert into car (id, model, make, year) values (52, 'Mazdaspeed6', 'Mazda', 2007);
insert into car (id, model, make, year) values (53, 'GL-Class', 'Mercedes-Benz', 2010);
insert into car (id, model, make, year) values (54, 'Ram 1500 Club', 'Dodge', 2001);
insert into car (id, model, make, year) values (55, 'Murano', 'Nissan', 2005);
insert into car (id, model, make, year) values (56, 'LR2', 'Land Rover', 2012);
insert into car (id, model, make, year) values (57, 'Wrangler', 'Jeep', 2010);
insert into car (id, model, make, year) values (58, 'Bonneville', 'Pontiac', 1999);
insert into car (id, model, make, year) values (59, 'IS', 'Lexus', 2012);
insert into car (id, model, make, year) values (60, 'Ascender', 'Isuzu', 2003);
insert into car (id, model, make, year) values (61, 'Tucson', 'Hyundai', 2010);
insert into car (id, model, make, year) values (62, 'Caprice Classic', 'Chevrolet', 1995);
insert into car (id, model, make, year) values (63, 'Regal', 'Buick', 1985);
insert into car (id, model, make, year) values (64, 'V70', 'Volvo', 2000);
insert into car (id, model, make, year) values (65, 'GX', 'Lexus', 2009);
insert into car (id, model, make, year) values (66, 'Century', 'Buick', 1992);
insert into car (id, model, make, year) values (67, 'Grand Caravan', 'Dodge', 2007);
insert into car (id, model, make, year) values (68, 'Tracker', 'Geo', 1996);
insert into car (id, model, make, year) values (69, 'XT', 'Subaru', 1991);
insert into car (id, model, make, year) values (70, '1500', 'GMC', 1994);
insert into car (id, model, make, year) values (71, 'S-Class', 'Mercedes-Benz', 2001);
insert into car (id, model, make, year) values (72, 'T100 Xtra', 'Toyota', 1996);
insert into car (id, model, make, year) values (73, 'Rodeo Sport', 'Isuzu', 2001);
insert into car (id, model, make, year) values (74, 'CX-7', 'Mazda', 2012);
insert into car (id, model, make, year) values (75, 'Sunbird', 'Pontiac', 1986);
insert into car (id, model, make, year) values (76, 'Club Wagon', 'Ford', 1993);
insert into car (id, model, make, year) values (77, 'Raider', 'Mitsubishi', 2009);
insert into car (id, model, make, year) values (78, 'Passport', 'Honda', 2002);
insert into car (id, model, make, year) values (79, 'Prizm', 'Chevrolet', 2001);
insert into car (id, model, make, year) values (80, 'MINI', 'MINI', 2002);
insert into car (id, model, make, year) values (81, 'Celica', 'Toyota', 1978);
insert into car (id, model, make, year) values (82, 'Swift', 'Suzuki', 1998);
insert into car (id, model, make, year) values (83, 'Festiva', 'Ford', 1993);
insert into car (id, model, make, year) values (84, 'Protege', 'Mazda', 1998);
insert into car (id, model, make, year) values (85, 'Solara', 'Toyota', 2006);
insert into car (id, model, make, year) values (86, 'Yukon', 'GMC', 2007);
insert into car (id, model, make, year) values (87, 'Aspire', 'Ford', 1995);
insert into car (id, model, make, year) values (88, 'Vantage', 'Aston Martin', 2011);
insert into car (id, model, make, year) values (89, 'Grand Prix', 'Pontiac', 1962);
insert into car (id, model, make, year) values (90, 'Navajo', 'Mazda', 1993);
insert into car (id, model, make, year) values (91, 'S-Class', 'Mercedes-Benz', 2003);
insert into car (id, model, make, year) values (92, 'Escape', 'Ford', 2010);
insert into car (id, model, make, year) values (93, 'Colt Vista', 'Plymouth', 1993);
insert into car (id, model, make, year) values (94, 'Regency', 'Oldsmobile', 1997);
insert into car (id, model, make, year) values (95, 'Grand Am', 'Pontiac', 1999);
insert into car (id, model, make, year) values (96, '323', 'Mazda', 1992);
insert into car (id, model, make, year) values (97, 'Murciélago', 'Lamborghini', 2006);
insert into car (id, model, make, year) values (98, 'H2', 'Hummer', 2006);
insert into car (id, model, make, year) values (99, 'CC', 'Volkswagen', 2010);
insert into car (id, model, make, year) values (100, 'X6', 'BMW', 2011);
insert into car (id, model, make, year) values (101, 'Touareg', 'Volkswagen', 2010);
insert into car (id, model, make, year) values (102, 'Savana 2500', 'GMC', 2010);
insert into car (id, model, make, year) values (103, 'VUE', 'Saturn', 2003);
insert into car (id, model, make, year) values (104, 'RL', 'Acura', 1998);
insert into car (id, model, make, year) values (105, 'Legacy', 'Subaru', 2004);
insert into car (id, model, make, year) values (106, 'Skylark', 'Buick', 1993);
insert into car (id, model, make, year) values (107, 'Express 3500', 'Chevrolet', 1999);
insert into car (id, model, make, year) values (108, 'Sidekick', 'Suzuki', 1990);
insert into car (id, model, make, year) values (109, 'Tacoma Xtra', 'Toyota', 2001);
insert into car (id, model, make, year) values (110, 'CL-Class', 'Mercedes-Benz', 2001);
insert into car (id, model, make, year) values (111, '8 Series', 'BMW', 1993);
insert into car (id, model, make, year) values (112, 'Grand Marquis', 'Mercury', 1992);
insert into car (id, model, make, year) values (113, '3 Series', 'BMW', 1993);
insert into car (id, model, make, year) values (114, '300', 'Chrysler', 2005);
insert into car (id, model, make, year) values (115, 'Lanos', 'Daewoo', 2000);
insert into car (id, model, make, year) values (116, '330', 'BMW', 2006);
insert into car (id, model, make, year) values (117, '9-3', 'Saab', 2004);
insert into car (id, model, make, year) values (118, '8 Series', 'BMW', 1996);
insert into car (id, model, make, year) values (119, 'R-Class', 'Mercedes-Benz', 2007);
insert into car (id, model, make, year) values (120, 'Odyssey', 'Honda', 2003);
insert into car (id, model, make, year) values (121, 'Bronco II', 'Ford', 1988);
insert into car (id, model, make, year) values (122, 'Dakota', 'Ram', 2011);
insert into car (id, model, make, year) values (123, 'Blackwood', 'Lincoln', 2003);
insert into car (id, model, make, year) values (124, 'Cherokee', 'Jeep', 1999);
insert into car (id, model, make, year) values (125, 'GTO', 'Mitsubishi', 1991);
insert into car (id, model, make, year) values (126, 'Mariner', 'Mercury', 2011);
insert into car (id, model, make, year) values (127, 'Century', 'Buick', 1985);
insert into car (id, model, make, year) values (128, 'Continental Flying Spur', 'Bentley', 2008);
insert into car (id, model, make, year) values (129, '3500', 'Chevrolet', 1992);
insert into car (id, model, make, year) values (130, 'Pajero', 'Mitsubishi', 1995);
insert into car (id, model, make, year) values (131, 'Prius', 'Toyota', 2008);
insert into car (id, model, make, year) values (132, 'MX-5', 'Mazda', 2006);
insert into car (id, model, make, year) values (133, 'Sportage', 'Kia', 2006);
insert into car (id, model, make, year) values (134, 'Escort', 'Ford', 1990);
insert into car (id, model, make, year) values (135, 'S4', 'Audi', 1992);
insert into car (id, model, make, year) values (136, 'Rally Wagon 3500', 'GMC', 1994);
insert into car (id, model, make, year) values (137, 'H3T', 'Hummer', 2010);
insert into car (id, model, make, year) values (138, 'Savana 3500', 'GMC', 2007);
insert into car (id, model, make, year) values (139, 'Armada', 'Nissan', 2012);
insert into car (id, model, make, year) values (140, '100', 'Audi', 1992);
insert into car (id, model, make, year) values (141, 'F250', 'Ford', 2002);
insert into car (id, model, make, year) values (142, 'S-Series', 'Saturn', 2002);
insert into car (id, model, make, year) values (143, 'GTI', 'Volkswagen', 1997);
insert into car (id, model, make, year) values (144, '5000S', 'Audi', 1987);
insert into car (id, model, make, year) values (145, 'Quest', 'Nissan', 2002);
insert into car (id, model, make, year) values (146, 'Corvette', 'Chevrolet', 1970);
insert into car (id, model, make, year) values (147, '190E', 'Mercedes-Benz', 1993);
insert into car (id, model, make, year) values (148, 'Suburban 2500', 'GMC', 1997);
insert into car (id, model, make, year) values (149, 'Tundra', 'Toyota', 2011);
insert into car (id, model, make, year) values (150, 'Grand Am', 'Pontiac', 2001);
insert into car (id, model, make, year) values (151, 'Sebring', 'Chrysler', 2010);
insert into car (id, model, make, year) values (152, 'SL-Class', 'Mercedes-Benz', 1996);
insert into car (id, model, make, year) values (153, 'W201', 'Mercedes-Benz', 1984);
insert into car (id, model, make, year) values (154, 'Astro', 'Chevrolet', 2005);
insert into car (id, model, make, year) values (155, 'Yukon XL 1500', 'GMC', 2013);
insert into car (id, model, make, year) values (156, 'Sephia', 'Kia', 1994);
insert into car (id, model, make, year) values (157, 'Avanti', 'Studebaker', 1962);
insert into car (id, model, make, year) values (158, 'PT Cruiser', 'Chrysler', 2004);
insert into car (id, model, make, year) values (159, 'Taurus', 'Ford', 2010);
insert into car (id, model, make, year) values (160, 'Explorer', 'Ford', 1994);
insert into car (id, model, make, year) values (161, 'riolet', 'Audi', 1996);
insert into car (id, model, make, year) values (162, 'Civic', 'Honda', 2009);
insert into car (id, model, make, year) values (163, 'SRX', 'Cadillac', 2004);
insert into car (id, model, make, year) values (164, 'Silverado 3500', 'Chevrolet', 2009);
insert into car (id, model, make, year) values (165, 'Terrain', 'GMC', 2012);
insert into car (id, model, make, year) values (166, 'Fusion', 'Ford', 2010);
insert into car (id, model, make, year) values (167, '900', 'Saab', 1993);
insert into car (id, model, make, year) values (168, 'GTI', 'Volkswagen', 1993);
insert into car (id, model, make, year) values (169, 'Scirocco', 'Volkswagen', 1988);
insert into car (id, model, make, year) values (170, 'Matrix', 'Toyota', 2008);
insert into car (id, model, make, year) values (171, 'Impreza', 'Subaru', 1996);
insert into car (id, model, make, year) values (172, 'TT', 'Audi', 2001);
insert into car (id, model, make, year) values (173, 'Frontier', 'Nissan', 2004);
insert into car (id, model, make, year) values (174, 'G', 'Infiniti', 1999);
insert into car (id, model, make, year) values (175, 'Grand Prix', 'Pontiac', 1989);
insert into car (id, model, make, year) values (176, 'EX', 'Infiniti', 2010);
insert into car (id, model, make, year) values (177, 'SLX', 'Acura', 1997);
insert into car (id, model, make, year) values (178, 'Cayman', 'Porsche', 2012);
insert into car (id, model, make, year) values (179, 'Beetle', 'Volkswagen', 1965);
insert into car (id, model, make, year) values (180, 'RX', 'Lexus', 2001);
insert into car (id, model, make, year) values (181, 'Impreza', 'Subaru', 2002);
insert into car (id, model, make, year) values (182, '3 Series', 'BMW', 1999);
insert into car (id, model, make, year) values (183, 'Bonneville', 'Pontiac', 2003);
insert into car (id, model, make, year) values (184, 'Ranger', 'Ford', 1992);
insert into car (id, model, make, year) values (185, 'Flex', 'Ford', 2009);
insert into car (id, model, make, year) values (186, 'Grand Marquis', 'Mercury', 2009);
insert into car (id, model, make, year) values (187, 'Cavalier', 'Chevrolet', 2005);
insert into car (id, model, make, year) values (188, 'Lucerne', 'Buick', 2007);
insert into car (id, model, make, year) values (189, 'Maxima', 'Nissan', 2001);
insert into car (id, model, make, year) values (190, 'Suburban 2500', 'Chevrolet', 2006);
insert into car (id, model, make, year) values (191, 'Boxster', 'Porsche', 2002);
insert into car (id, model, make, year) values (192, 'Quantum', 'Volkswagen', 1984);
insert into car (id, model, make, year) values (193, 'RX-7', 'Mazda', 1983);
insert into car (id, model, make, year) values (194, 'Grand Am', 'Pontiac', 1995);
insert into car (id, model, make, year) values (195, 'Grand Prix', 'Pontiac', 2000);
insert into car (id, model, make, year) values (196, '928', 'Porsche', 1987);
insert into car (id, model, make, year) values (197, 'C-Class', 'Mercedes-Benz', 1997);
insert into car (id, model, make, year) values (198, 'Grand Marquis', 'Mercury', 2010);
insert into car (id, model, make, year) values (199, 'Mustang', 'Ford', 1996);
insert into car (id, model, make, year) values (200, 'Town & Country', 'Chrysler', 2011);
insert into car (id, model, make, year) values (201, 'Exige', 'Lotus', 2011);
insert into car (id, model, make, year) values (202, 'A6', 'Audi', 2008);
insert into car (id, model, make, year) values (203, 'Camaro', 'Chevrolet', 1993);
insert into car (id, model, make, year) values (204, 'Azera', 'Hyundai', 2009);
insert into car (id, model, make, year) values (205, 'Continental Mark VII', 'Lincoln', 1990);
insert into car (id, model, make, year) values (206, 'V90', 'Volvo', 1998);
insert into car (id, model, make, year) values (207, 'DB9', 'Aston Martin', 2012);
insert into car (id, model, make, year) values (208, 'LeMans', 'Pontiac', 1991);
insert into car (id, model, make, year) values (209, 'Frontier', 'Nissan', 2010);
insert into car (id, model, make, year) values (210, 'M', 'Infiniti', 2006);
insert into car (id, model, make, year) values (211, 'RX Hybrid', 'Lexus', 2006);
insert into car (id, model, make, year) values (212, 'Gallardo', 'Lamborghini', 2003);
insert into car (id, model, make, year) values (213, 'Cavalier', 'Chevrolet', 2003);
insert into car (id, model, make, year) values (214, 'Windstar', 'Ford', 2002);
insert into car (id, model, make, year) values (215, 'Tahoe', 'Chevrolet', 1996);
insert into car (id, model, make, year) values (216, 'Swift', 'Suzuki', 1996);
insert into car (id, model, make, year) values (217, 'Bravada', 'Oldsmobile', 2001);
insert into car (id, model, make, year) values (218, 'XG350', 'Hyundai', 2005);
insert into car (id, model, make, year) values (219, 'Titan', 'Nissan', 2007);
insert into car (id, model, make, year) values (220, 'F450', 'Ford', 2011);
insert into car (id, model, make, year) values (221, 'Regal', 'Buick', 1993);
insert into car (id, model, make, year) values (222, 'Cobalt', 'Chevrolet', 2008);
insert into car (id, model, make, year) values (223, 'Corvette', 'Chevrolet', 1994);
insert into car (id, model, make, year) values (224, 'RAV4', 'Toyota', 1997);
insert into car (id, model, make, year) values (225, 'Touareg', 'Volkswagen', 2010);
insert into car (id, model, make, year) values (226, 'Z8', 'BMW', 2002);
insert into car (id, model, make, year) values (227, 'Escort', 'Ford', 2004);
insert into car (id, model, make, year) values (228, 'Solstice', 'Pontiac', 2006);
insert into car (id, model, make, year) values (229, 'Escalade EXT', 'Cadillac', 2005);
insert into car (id, model, make, year) values (230, 'DB9', 'Aston Martin', 2007);
insert into car (id, model, make, year) values (231, 'Sable', 'Mercury', 1989);
insert into car (id, model, make, year) values (232, 'Suburban 1500', 'GMC', 1995);
insert into car (id, model, make, year) values (233, 'Avalanche 1500', 'Chevrolet', 2002);
insert into car (id, model, make, year) values (234, 'Stealth', 'Dodge', 1995);
insert into car (id, model, make, year) values (235, 'Oasis', 'Isuzu', 1996);
insert into car (id, model, make, year) values (236, 'Jimmy', 'GMC', 1994);
insert into car (id, model, make, year) values (237, '5000CS', 'Audi', 1987);
insert into car (id, model, make, year) values (238, 'Ascender', 'Isuzu', 2008);
insert into car (id, model, make, year) values (239, 'C70', 'Volvo', 2002);
insert into car (id, model, make, year) values (240, 'XJ Series', 'Jaguar', 1994);
insert into car (id, model, make, year) values (241, '430', 'Maserati', 1991);
insert into car (id, model, make, year) values (242, 'xD', 'Scion', 2011);
insert into car (id, model, make, year) values (243, '5 Series', 'BMW', 1993);
insert into car (id, model, make, year) values (244, 'Ranger', 'Ford', 2004);
insert into car (id, model, make, year) values (245, 'Tahoe', 'Chevrolet', 2006);
insert into car (id, model, make, year) values (246, 'Grand Am', 'Pontiac', 1993);
insert into car (id, model, make, year) values (247, 'Probe', 'Ford', 1990);
insert into car (id, model, make, year) values (248, 'H1', 'Hummer', 1997);
insert into car (id, model, make, year) values (249, 'V70', 'Volvo', 2001);
insert into car (id, model, make, year) values (250, 'M', 'Infiniti', 2004);
insert into car (id, model, make, year) values (251, 'MKT', 'Lincoln', 2012);
insert into car (id, model, make, year) values (252, 'Excursion', 'Ford', 2002);
insert into car (id, model, make, year) values (253, 'XK Series', 'Jaguar', 1997);
insert into car (id, model, make, year) values (254, 'Viper', 'Dodge', 1999);
insert into car (id, model, make, year) values (255, 'Mohave/Borrego', 'Kia', 2009);
insert into car (id, model, make, year) values (256, 'Protege', 'Mazda', 1992);
insert into car (id, model, make, year) values (257, 'Solstice', 'Pontiac', 2008);
insert into car (id, model, make, year) values (258, 'MKZ', 'Lincoln', 2009);
insert into car (id, model, make, year) values (259, 'Solara', 'Toyota', 2008);
insert into car (id, model, make, year) values (260, 'Land Cruiser', 'Toyota', 2008);
insert into car (id, model, make, year) values (261, 'RX', 'Lexus', 2001);
insert into car (id, model, make, year) values (262, '960', 'Volvo', 1996);
insert into car (id, model, make, year) values (263, 'Rapide', 'Aston Martin', 2011);
insert into car (id, model, make, year) values (264, 'New Beetle', 'Volkswagen', 2003);
insert into car (id, model, make, year) values (265, 'S-Class', 'Mercedes-Benz', 1985);
insert into car (id, model, make, year) values (266, 'Bonneville', 'Pontiac', 1991);
insert into car (id, model, make, year) values (267, 'Mustang', 'Ford', 2008);
insert into car (id, model, make, year) values (268, '9-5', 'Saab', 1999);
insert into car (id, model, make, year) values (269, 'Grand Marquis', 'Mercury', 1989);
insert into car (id, model, make, year) values (270, 'S-Series', 'Saturn', 2002);
insert into car (id, model, make, year) values (271, 'Ram 2500', 'Dodge', 2005);
insert into car (id, model, make, year) values (272, 'LHS', 'Chrysler', 2000);
insert into car (id, model, make, year) values (273, 'E-Series', 'Ford', 2006);
insert into car (id, model, make, year) values (274, 'Z3', 'BMW', 1998);
insert into car (id, model, make, year) values (275, 'A6', 'Audi', 1999);
insert into car (id, model, make, year) values (276, 'J', 'Infiniti', 1997);
insert into car (id, model, make, year) values (277, '1500', 'Chevrolet', 1996);
insert into car (id, model, make, year) values (278, 'S60', 'Volvo', 2006);
insert into car (id, model, make, year) values (279, 'Q', 'Infiniti', 2000);
insert into car (id, model, make, year) values (280, 'Sidekick', 'Suzuki', 1997);
insert into car (id, model, make, year) values (281, 'Exige', 'Lotus', 2012);
insert into car (id, model, make, year) values (282, 'Altima', 'Nissan', 2013);
insert into car (id, model, make, year) values (283, 'Impala', 'Chevrolet', 2006);
insert into car (id, model, make, year) values (284, 'Wrangler', 'Jeep', 2001);
insert into car (id, model, make, year) values (285, 'Murano', 'Nissan', 2011);
insert into car (id, model, make, year) values (286, 'S-Type', 'Jaguar', 2001);
insert into car (id, model, make, year) values (287, '911', 'Porsche', 2006);
insert into car (id, model, make, year) values (288, 'TSX', 'Acura', 2007);
insert into car (id, model, make, year) values (289, 'Typ-1', 'Aptera', 2008);
insert into car (id, model, make, year) values (290, 'Highlander', 'Toyota', 2003);
insert into car (id, model, make, year) values (291, 'Ram Van 1500', 'Dodge', 2000);
insert into car (id, model, make, year) values (292, 'Silhouette', 'Oldsmobile', 2000);
insert into car (id, model, make, year) values (293, 'Tempo', 'Ford', 1988);
insert into car (id, model, make, year) values (294, 'Civic', 'Honda', 1996);
insert into car (id, model, make, year) values (295, 'Hemisfear', 'Foose', 2007);
insert into car (id, model, make, year) values (296, 'Tracer', 'Mercury', 1991);
insert into car (id, model, make, year) values (297, 'Sonata', 'Hyundai', 2013);
insert into car (id, model, make, year) values (298, 'New Beetle', 'Volkswagen', 2006);
insert into car (id, model, make, year) values (299, 'S40', 'Volvo', 2004);
insert into car (id, model, make, year) values (300, 'Taurus', 'Ford', 1996);
insert into car (id, model, make, year) values (301, 'Cutlass Supreme', 'Oldsmobile', 1996);
insert into car (id, model, make, year) values (302, 'Edge', 'Ford', 2011);
insert into car (id, model, make, year) values (303, 'Savana 3500', 'GMC', 2010);
insert into car (id, model, make, year) values (304, 'Windstar', 'Ford', 2002);
insert into car (id, model, make, year) values (305, 'H3', 'Hummer', 2010);
insert into car (id, model, make, year) values (306, 'Ram Van 3500', 'Dodge', 2003);
insert into car (id, model, make, year) values (307, 'X5', 'BMW', 2005);
insert into car (id, model, make, year) values (308, 'Town & Country', 'Chrysler', 1999);
insert into car (id, model, make, year) values (309, 'Civic', 'Honda', 1989);
insert into car (id, model, make, year) values (310, 'Mustang', 'Ford', 1985);
insert into car (id, model, make, year) values (311, 'SRX', 'Cadillac', 2009);
insert into car (id, model, make, year) values (312, '9000', 'Saab', 1997);
insert into car (id, model, make, year) values (313, 'M6', 'BMW', 2009);
insert into car (id, model, make, year) values (314, '911', 'Porsche', 1998);
insert into car (id, model, make, year) values (315, 'Land Cruiser', 'Toyota', 2009);
insert into car (id, model, make, year) values (316, 'M3', 'BMW', 2006);
insert into car (id, model, make, year) values (317, 'Jetta', 'Volkswagen', 1992);
insert into car (id, model, make, year) values (318, 'S40', 'Volvo', 2001);
insert into car (id, model, make, year) values (319, 'MPV', 'Mazda', 2000);
insert into car (id, model, make, year) values (320, 'XJ', 'Jaguar', 2010);
insert into car (id, model, make, year) values (321, 'VUE', 'Saturn', 2008);
insert into car (id, model, make, year) values (322, 'EXP', 'Ford', 1984);
insert into car (id, model, make, year) values (323, 'Cayenne', 'Porsche', 2011);
insert into car (id, model, make, year) values (324, 'Econoline E150', 'Ford', 1993);
insert into car (id, model, make, year) values (325, 'Voyager', 'Chrysler', 2001);
insert into car (id, model, make, year) values (326, 'H1', 'Hummer', 2001);
insert into car (id, model, make, year) values (327, 'Quest', 'Nissan', 1994);
insert into car (id, model, make, year) values (328, 'Rondo', 'Kia', 2010);
insert into car (id, model, make, year) values (329, 'Mystique', 'Mercury', 1999);
insert into car (id, model, make, year) values (330, 'Interceptor', 'Jensen', 1967);
insert into car (id, model, make, year) values (331, 'MR2', 'Toyota', 2000);
insert into car (id, model, make, year) values (332, '9-7X', 'Saab', 2006);
insert into car (id, model, make, year) values (333, 'Aerostar', 'Ford', 1987);
insert into car (id, model, make, year) values (334, 'F-Series', 'Ford', 2005);
insert into car (id, model, make, year) values (335, 'TrailBlazer', 'Chevrolet', 2007);
insert into car (id, model, make, year) values (336, 'Titan', 'Nissan', 2011);
insert into car (id, model, make, year) values (337, 'Impala', 'Chevrolet', 2007);
insert into car (id, model, make, year) values (338, 'S40', 'Volvo', 2005);
insert into car (id, model, make, year) values (339, 'RAV4', 'Toyota', 1996);
insert into car (id, model, make, year) values (340, '5 Series', 'BMW', 2012);
insert into car (id, model, make, year) values (341, 'Navigator', 'Lincoln', 2008);
insert into car (id, model, make, year) values (342, '6000', 'Pontiac', 1987);
insert into car (id, model, make, year) values (343, 'Ram Van 1500', 'Dodge', 2002);
insert into car (id, model, make, year) values (344, 'Suburban 2500', 'Chevrolet', 2001);
insert into car (id, model, make, year) values (345, 'Z4', 'BMW', 2008);
insert into car (id, model, make, year) values (346, 'Ram 3500', 'Dodge', 2009);
insert into car (id, model, make, year) values (347, 'QX56', 'Infiniti', 2012);
insert into car (id, model, make, year) values (348, 'Sierra 1500', 'GMC', 2002);
insert into car (id, model, make, year) values (349, 'ES', 'Lexus', 2010);
insert into car (id, model, make, year) values (350, '1500 Club Coupe', 'GMC', 1999);
insert into car (id, model, make, year) values (351, 'Land Cruiser', 'Toyota', 2004);
insert into car (id, model, make, year) values (352, 'GranSport', 'Maserati', 2005);
insert into car (id, model, make, year) values (353, 'G', 'Infiniti', 2003);
insert into car (id, model, make, year) values (354, 'S40', 'Volvo', 2001);
insert into car (id, model, make, year) values (355, 'Corvette', 'Chevrolet', 1961);
insert into car (id, model, make, year) values (356, '300ZX', 'Nissan', 1993);
insert into car (id, model, make, year) values (357, 'Avanti', 'Studebaker', 1963);
insert into car (id, model, make, year) values (358, 'Neon', 'Plymouth', 1995);
insert into car (id, model, make, year) values (359, 'Accord', 'Honda', 1997);
insert into car (id, model, make, year) values (360, 'Caprice', 'Chevrolet', 1983);
insert into car (id, model, make, year) values (361, 'Caprice', 'Chevrolet', 1994);
insert into car (id, model, make, year) values (362, 'M3', 'BMW', 2011);
insert into car (id, model, make, year) values (363, 'Legacy', 'Subaru', 1996);
insert into car (id, model, make, year) values (364, 'V40', 'Volvo', 2004);
insert into car (id, model, make, year) values (365, 'Aerio', 'Suzuki', 2007);
insert into car (id, model, make, year) values (366, '4000s', 'Audi', 1986);
insert into car (id, model, make, year) values (367, 'Mariner', 'Mercury', 2005);
insert into car (id, model, make, year) values (368, 'E-Series', 'Ford', 2005);
insert into car (id, model, make, year) values (369, 'Tracer', 'Mercury', 1989);
insert into car (id, model, make, year) values (370, 'Stratus', 'Dodge', 1999);
insert into car (id, model, make, year) values (371, 'Yukon', 'GMC', 2009);
insert into car (id, model, make, year) values (372, 'Wrangler', 'Jeep', 2004);
insert into car (id, model, make, year) values (373, 'Outback', 'Subaru', 2010);
insert into car (id, model, make, year) values (374, 'Tiburon', 'Hyundai', 2003);
insert into car (id, model, make, year) values (375, 'I', 'Infiniti', 2003);
insert into car (id, model, make, year) values (376, 'Grand Prix', 'Pontiac', 1980);
insert into car (id, model, make, year) values (377, 'Land Cruiser', 'Toyota', 2000);
insert into car (id, model, make, year) values (378, 'Bonneville', 'Pontiac', 1986);
insert into car (id, model, make, year) values (379, 'Truck', 'Mitsubishi', 1992);
insert into car (id, model, make, year) values (380, 'Explorer', 'Ford', 2005);
insert into car (id, model, make, year) values (381, 'TT', 'Audi', 2011);
insert into car (id, model, make, year) values (382, 'Festiva', 'Ford', 1990);
insert into car (id, model, make, year) values (383, 'Accord', 'Honda', 1983);
insert into car (id, model, make, year) values (384, 'Odyssey', 'Honda', 2011);
insert into car (id, model, make, year) values (385, 'Q7', 'Audi', 2008);
insert into car (id, model, make, year) values (386, 'Galant', 'Mitsubishi', 2010);
insert into car (id, model, make, year) values (387, 'Explorer', 'Ford', 1998);
insert into car (id, model, make, year) values (388, 'B-Series', 'Mazda', 1994);
insert into car (id, model, make, year) values (389, 'Outback', 'Subaru', 2010);
insert into car (id, model, make, year) values (390, 'Defender', 'Land Rover', 1995);
insert into car (id, model, make, year) values (391, 'Ridgeline', 'Honda', 2006);
insert into car (id, model, make, year) values (392, 'Galant', 'Mitsubishi', 1990);
insert into car (id, model, make, year) values (393, 'Challenger', 'Dodge', 2012);
insert into car (id, model, make, year) values (394, 'Thunderbird', 'Ford', 1990);
insert into car (id, model, make, year) values (395, 'RX', 'Lexus', 2012);
insert into car (id, model, make, year) values (396, 'Legend', 'Acura', 1987);
insert into car (id, model, make, year) values (397, 'X-Type', 'Jaguar', 2004);
insert into car (id, model, make, year) values (398, 'Transit Connect', 'Ford', 2013);
insert into car (id, model, make, year) values (399, 'E-Series', 'Ford', 2009);
insert into car (id, model, make, year) values (400, 'Sedona', 'Kia', 2006);
insert into car (id, model, make, year) values (401, 'Range Rover', 'Land Rover', 2005);
insert into car (id, model, make, year) values (402, 'CL-Class', 'Mercedes-Benz', 2007);
insert into car (id, model, make, year) values (403, 'Diamante', 'Mitsubishi', 2002);
insert into car (id, model, make, year) values (404, 'M3', 'BMW', 2004);
insert into car (id, model, make, year) values (405, '9-5', 'Saab', 2004);
insert into car (id, model, make, year) values (406, 'Odyssey', 'Honda', 2003);
insert into car (id, model, make, year) values (407, 'Impreza', 'Subaru', 2011);
insert into car (id, model, make, year) values (408, 'Town Car', 'Lincoln', 2011);
insert into car (id, model, make, year) values (409, '90', 'Audi', 1994);
insert into car (id, model, make, year) values (410, 'Q5', 'Audi', 2010);
insert into car (id, model, make, year) values (411, 'Grand Prix', 'Pontiac', 1982);
insert into car (id, model, make, year) values (412, 'Yukon XL 2500', 'GMC', 2010);
insert into car (id, model, make, year) values (413, 'GranTurismo', 'Maserati', 2011);
insert into car (id, model, make, year) values (414, 'GTO', 'Mitsubishi', 1991);
insert into car (id, model, make, year) values (415, 'Evora', 'Lotus', 2012);
insert into car (id, model, make, year) values (416, 'Cougar', 'Mercury', 1991);
insert into car (id, model, make, year) values (417, 'Frontier', 'Nissan', 2003);
insert into car (id, model, make, year) values (418, 'Quattro', 'Audi', 1992);
insert into car (id, model, make, year) values (419, 'SLK-Class', 'Mercedes-Benz', 2004);
insert into car (id, model, make, year) values (420, 'Forester', 'Subaru', 2010);
insert into car (id, model, make, year) values (421, 'Tracker', 'Geo', 1993);
insert into car (id, model, make, year) values (422, 'Civic', 'Honda', 2001);
insert into car (id, model, make, year) values (423, 'Sierra 1500', 'GMC', 1999);
insert into car (id, model, make, year) values (424, 'Terrain', 'GMC', 2012);
insert into car (id, model, make, year) values (425, '6 Series', 'BMW', 2009);
insert into car (id, model, make, year) values (426, 'Commander', 'Jeep', 2009);
insert into car (id, model, make, year) values (427, '3 Series', 'BMW', 2001);
insert into car (id, model, make, year) values (428, 'Legacy', 'Subaru', 1989);
insert into car (id, model, make, year) values (429, 'Space', 'Isuzu', 1993);
insert into car (id, model, make, year) values (430, 'Quattroporte', 'Maserati', 2007);
insert into car (id, model, make, year) values (431, 'Celica', 'Toyota', 2004);
insert into car (id, model, make, year) values (432, 'Caravan', 'Dodge', 1992);
insert into car (id, model, make, year) values (433, 'S-Class', 'Mercedes-Benz', 1991);
insert into car (id, model, make, year) values (434, 'Vantage', 'Aston Martin', 2007);
insert into car (id, model, make, year) values (435, 'Tacoma', 'Toyota', 2010);
insert into car (id, model, make, year) values (436, 'Integra', 'Acura', 2000);
insert into car (id, model, make, year) values (437, 'GX', 'Lexus', 2003);
insert into car (id, model, make, year) values (438, 'Equinox', 'Chevrolet', 2008);
insert into car (id, model, make, year) values (439, 'Model S', 'Tesla', 2012);
insert into car (id, model, make, year) values (440, 'Pilot', 'Honda', 2003);
insert into car (id, model, make, year) values (441, 'S60', 'Volvo', 2006);
insert into car (id, model, make, year) values (442, 'Camaro', 'Chevrolet', 1975);
insert into car (id, model, make, year) values (443, 'Galant', 'Mitsubishi', 1984);
insert into car (id, model, make, year) values (444, 'Focus', 'Ford', 2004);
insert into car (id, model, make, year) values (445, 'Maxima', 'Nissan', 2004);
insert into car (id, model, make, year) values (446, 'Suburban 2500', 'GMC', 1994);
insert into car (id, model, make, year) values (447, 'Neon', 'Dodge', 2005);
insert into car (id, model, make, year) values (448, 'XT', 'Subaru', 1985);
insert into car (id, model, make, year) values (449, 'Tempo', 'Ford', 1993);
insert into car (id, model, make, year) values (450, 'F-Series', 'Ford', 2002);
insert into car (id, model, make, year) values (451, 'Tahoe', 'Chevrolet', 1996);
insert into car (id, model, make, year) values (452, 'C-Class', 'Mercedes-Benz', 1994);
insert into car (id, model, make, year) values (453, 'TL', 'Acura', 2005);
insert into car (id, model, make, year) values (454, 'S-Type', 'Jaguar', 2002);
insert into car (id, model, make, year) values (455, 'Diamante', 'Mitsubishi', 1998);
insert into car (id, model, make, year) values (456, 'Grand Prix', 'Pontiac', 1986);
insert into car (id, model, make, year) values (457, 'G', 'Infiniti', 2002);
insert into car (id, model, make, year) values (458, 'B-Series', 'Mazda', 2007);
insert into car (id, model, make, year) values (459, 'Continental', 'Lincoln', 1993);
insert into car (id, model, make, year) values (460, 'Brat', 'Subaru', 1984);
insert into car (id, model, make, year) values (461, 'Celica', 'Toyota', 2002);
insert into car (id, model, make, year) values (462, 'Paseo', 'Toyota', 1996);
insert into car (id, model, make, year) values (463, '911', 'Porsche', 1986);
insert into car (id, model, make, year) values (464, 'Alero', 'Oldsmobile', 1999);
insert into car (id, model, make, year) values (465, 'FX', 'Infiniti', 2009);
insert into car (id, model, make, year) values (466, 'Montero Sport', 'Mitsubishi', 2003);
insert into car (id, model, make, year) values (467, '2e', 'Aptera', 2009);
insert into car (id, model, make, year) values (468, 'Bravada', 'Oldsmobile', 2004);
insert into car (id, model, make, year) values (469, 'Rally Wagon 1500', 'GMC', 1992);
insert into car (id, model, make, year) values (470, 'Grand Cherokee', 'Jeep', 1993);
insert into car (id, model, make, year) values (471, 'Daewoo Magnus', 'Suzuki', 2006);
insert into car (id, model, make, year) values (472, 'Focus', 'Ford', 2012);
insert into car (id, model, make, year) values (473, 'Ram 1500 Club', 'Dodge', 1996);
insert into car (id, model, make, year) values (474, 'Tracker', 'Geo', 1995);
insert into car (id, model, make, year) values (475, '929', 'Mazda', 1992);
insert into car (id, model, make, year) values (476, 'CL-Class', 'Mercedes-Benz', 1998);
insert into car (id, model, make, year) values (477, '240SX', 'Nissan', 1995);
insert into car (id, model, make, year) values (478, 'Cherokee', 'Jeep', 1998);
insert into car (id, model, make, year) values (479, 'i-MiEV', 'Mitsubishi', 2012);
insert into car (id, model, make, year) values (480, 'Wrangler', 'Jeep', 2005);
insert into car (id, model, make, year) values (481, 'Ciera', 'Oldsmobile', 1992);
insert into car (id, model, make, year) values (482, 'Jetta', 'Volkswagen', 2002);
insert into car (id, model, make, year) values (483, 'Concorde', 'Chrysler', 2000);
insert into car (id, model, make, year) values (484, '300SD', 'Mercedes-Benz', 1992);
insert into car (id, model, make, year) values (485, 'Avenger', 'Dodge', 2011);
insert into car (id, model, make, year) values (486, 'Avanti', 'Studebaker', 1964);
insert into car (id, model, make, year) values (487, 'Equus', 'Hyundai', 2013);
insert into car (id, model, make, year) values (488, 'Sequoia', 'Toyota', 2006);
insert into car (id, model, make, year) values (489, 'F250', 'Ford', 1992);
insert into car (id, model, make, year) values (490, 'M', 'Infiniti', 2009);
insert into car (id, model, make, year) values (491, 'Grand Marquis', 'Mercury', 1992);
insert into car (id, model, make, year) values (492, 'G6', 'Pontiac', 2009);
insert into car (id, model, make, year) values (493, 'Solara', 'Toyota', 2004);
insert into car (id, model, make, year) values (494, 'Expo LRV', 'Mitsubishi', 1996);
insert into car (id, model, make, year) values (495, 'Rockette', 'Fairthorpe', 1960);
insert into car (id, model, make, year) values (496, '1500', 'Chevrolet', 1998);
insert into car (id, model, make, year) values (497, 'Range Rover', 'Land Rover', 1990);
insert into car (id, model, make, year) values (498, 'Suburban 2500', 'GMC', 1993);
insert into car (id, model, make, year) values (499, 'Milan', 'Mercury', 2008);
insert into car (id, model, make, year) values (500, 'Yukon', 'GMC', 2001);
insert into car (id, model, make, year) values (501, 'Quattro', 'Audi', 1992);
insert into car (id, model, make, year) values (502, 'Savana 2500', 'GMC', 1996);
insert into car (id, model, make, year) values (503, 'LeMans', 'Pontiac', 1968);
insert into car (id, model, make, year) values (504, 'Sienna', 'Toyota', 2010);
insert into car (id, model, make, year) values (505, 'Phantom', 'Rolls-Royce', 2013);
insert into car (id, model, make, year) values (506, 'C70', 'Volvo', 2003);
insert into car (id, model, make, year) values (507, 'G-Series G10', 'Chevrolet', 1994);
insert into car (id, model, make, year) values (508, 'Toronado', 'Oldsmobile', 1966);
insert into car (id, model, make, year) values (509, 'Rio5', 'Kia', 2008);
insert into car (id, model, make, year) values (510, 'S40', 'Volvo', 2003);
insert into car (id, model, make, year) values (511, 'Passport', 'Honda', 1995);
insert into car (id, model, make, year) values (512, 'Suburban 1500', 'Chevrolet', 2000);
insert into car (id, model, make, year) values (513, 'MDX', 'Acura', 2008);
insert into car (id, model, make, year) values (514, 'Karif', 'Maserati', 1990);
insert into car (id, model, make, year) values (515, 'CLK-Class', 'Mercedes-Benz', 2005);
insert into car (id, model, make, year) values (516, 'Ipsum', 'Toyota', 2000);
insert into car (id, model, make, year) values (517, 'Gallardo', 'Lamborghini', 2006);
insert into car (id, model, make, year) values (518, 'XL7', 'Suzuki', 2006);
insert into car (id, model, make, year) values (519, 'LS', 'Lexus', 2011);
insert into car (id, model, make, year) values (520, 'Galant', 'Mitsubishi', 1999);
insert into car (id, model, make, year) values (521, 'Monte Carlo', 'Chevrolet', 2007);
insert into car (id, model, make, year) values (522, '5 Series', 'BMW', 1994);
insert into car (id, model, make, year) values (523, 'XT', 'Subaru', 1985);
insert into car (id, model, make, year) values (524, 'Legacy', 'Subaru', 2005);
insert into car (id, model, make, year) values (525, 'Summit', 'Eagle', 1993);
insert into car (id, model, make, year) values (526, 'GL-Class', 'Mercedes-Benz', 2009);
insert into car (id, model, make, year) values (527, 'S2000', 'Honda', 2003);
insert into car (id, model, make, year) values (528, 'Talon', 'Eagle', 1993);
insert into car (id, model, make, year) values (529, 'Charger', 'Dodge', 2009);
insert into car (id, model, make, year) values (530, '1500', 'GMC', 1996);
insert into car (id, model, make, year) values (531, 'Tribute', 'Mazda', 2006);
insert into car (id, model, make, year) values (532, 'Edge', 'Ford', 2008);
insert into car (id, model, make, year) values (533, 'Ranger', 'Ford', 1984);
insert into car (id, model, make, year) values (534, 'Tacoma Xtra', 'Toyota', 2000);
insert into car (id, model, make, year) values (535, 'Carens', 'Kia', 2008);
insert into car (id, model, make, year) values (536, 'Mark LT', 'Lincoln', 2008);
insert into car (id, model, make, year) values (537, 'Prius', 'Toyota', 2007);
insert into car (id, model, make, year) values (538, 'Accord', 'Honda', 2005);
insert into car (id, model, make, year) values (539, 'Grand Am', 'Pontiac', 2003);
insert into car (id, model, make, year) values (540, 'Viper', 'Dodge', 2004);
insert into car (id, model, make, year) values (541, 'Neon', 'Plymouth', 1998);
insert into car (id, model, make, year) values (542, 'Summit', 'Eagle', 1992);
insert into car (id, model, make, year) values (543, 'MX-5', 'Mazda', 2007);
insert into car (id, model, make, year) values (544, 'Aveo', 'Chevrolet', 2011);
insert into car (id, model, make, year) values (545, 'Avalon', 'Toyota', 1996);
insert into car (id, model, make, year) values (546, 'Jetta', 'Volkswagen', 1989);
insert into car (id, model, make, year) values (547, 'Stratus', 'Dodge', 2003);
insert into car (id, model, make, year) values (548, 'W201', 'Mercedes-Benz', 1986);
insert into car (id, model, make, year) values (549, 'LHS', 'Chrysler', 1994);
insert into car (id, model, make, year) values (550, 'Viper', 'Dodge', 1998);
insert into car (id, model, make, year) values (551, 'Accent', 'Hyundai', 2012);
insert into car (id, model, make, year) values (552, 'Suburban 1500', 'GMC', 1993);
insert into car (id, model, make, year) values (553, 'XG350', 'Hyundai', 2005);
insert into car (id, model, make, year) values (554, 'Century', 'Buick', 1984);
insert into car (id, model, make, year) values (555, 'Prius', 'Toyota', 2012);
insert into car (id, model, make, year) values (556, '928', 'Porsche', 1989);
insert into car (id, model, make, year) values (557, '928', 'Porsche', 1993);
insert into car (id, model, make, year) values (558, 'X5', 'BMW', 2002);
insert into car (id, model, make, year) values (559, 'Riviera', 'Buick', 1991);
insert into car (id, model, make, year) values (560, 'Outlander', 'Mitsubishi', 2009);
insert into car (id, model, make, year) values (561, 'Corvette', 'Chevrolet', 1964);
insert into car (id, model, make, year) values (562, 'Coupe', 'Maserati', 2006);
insert into car (id, model, make, year) values (563, 'Town Car', 'Lincoln', 1999);
insert into car (id, model, make, year) values (564, 'Montero Sport', 'Mitsubishi', 2001);
insert into car (id, model, make, year) values (565, 'Cutlass Supreme', 'Oldsmobile', 1994);
insert into car (id, model, make, year) values (566, 'Hombre', 'Isuzu', 2000);
insert into car (id, model, make, year) values (567, 'Ghost', 'Rolls-Royce', 2011);
insert into car (id, model, make, year) values (568, 'Lucerne', 'Buick', 2007);
insert into car (id, model, make, year) values (569, 'Regal', 'Buick', 1986);
insert into car (id, model, make, year) values (570, 'Esprit', 'Lotus', 1985);
insert into car (id, model, make, year) values (571, 'Silverado 3500', 'Chevrolet', 2010);
insert into car (id, model, make, year) values (572, 'Town & Country', 'Chrysler', 2006);
insert into car (id, model, make, year) values (573, 'Town & Country', 'Chrysler', 2011);
insert into car (id, model, make, year) values (574, 'RL', 'Acura', 2002);
insert into car (id, model, make, year) values (575, 'Pilot', 'Honda', 2012);
insert into car (id, model, make, year) values (576, 'GX', 'Lexus', 2004);
insert into car (id, model, make, year) values (577, '626', 'Mazda', 1984);
insert into car (id, model, make, year) values (578, 'Accent', 'Hyundai', 1997);
insert into car (id, model, make, year) values (579, '900', 'Saab', 1992);
insert into car (id, model, make, year) values (580, 'Clubman', 'MINI', 2010);
insert into car (id, model, make, year) values (581, 'L300', 'Mitsubishi', 1987);
insert into car (id, model, make, year) values (582, 'Insight', 'Honda', 2010);
insert into car (id, model, make, year) values (583, 'GranTurismo', 'Maserati', 2012);
insert into car (id, model, make, year) values (584, 'Blazer', 'Chevrolet', 2005);
insert into car (id, model, make, year) values (585, 'Villager', 'Mercury', 1993);
insert into car (id, model, make, year) values (586, 'Dakota', 'Dodge', 2004);
insert into car (id, model, make, year) values (587, 'LTD Crown Victoria', 'Ford', 1986);
insert into car (id, model, make, year) values (588, 'Montana', 'Pontiac', 2003);
insert into car (id, model, make, year) values (589, '57', 'Maybach', 2007);
insert into car (id, model, make, year) values (590, 'Pathfinder Armada', 'Nissan', 2004);
insert into car (id, model, make, year) values (591, 'Vitara', 'Suzuki', 1999);
insert into car (id, model, make, year) values (592, 'Tahoe', 'Chevrolet', 2001);
insert into car (id, model, make, year) values (593, 'C/V', 'Ram', 2012);
insert into car (id, model, make, year) values (594, 'Durango', 'Dodge', 2008);
insert into car (id, model, make, year) values (595, 'Compass', 'Jeep', 2009);
insert into car (id, model, make, year) values (596, 'Yukon XL 2500', 'GMC', 2002);
insert into car (id, model, make, year) values (597, 'Spectra', 'Kia', 2002);
insert into car (id, model, make, year) values (598, 'B-Series Plus', 'Mazda', 1994);
insert into car (id, model, make, year) values (599, 'Odyssey', 'Honda', 2006);
insert into car (id, model, make, year) values (600, 'Daewoo Magnus', 'Suzuki', 2005);
insert into car (id, model, make, year) values (601, 'Daewoo Lacetti', 'Suzuki', 2008);
insert into car (id, model, make, year) values (602, 'Thunderbird', 'Ford', 1983);
insert into car (id, model, make, year) values (603, '2500', 'GMC', 1992);
insert into car (id, model, make, year) values (604, 'Sprinter', 'Dodge', 2009);
insert into car (id, model, make, year) values (605, 'X-Type', 'Jaguar', 2008);
insert into car (id, model, make, year) values (606, 'MR2', 'Toyota', 2003);
insert into car (id, model, make, year) values (607, 'Milan', 'Mercury', 2009);
insert into car (id, model, make, year) values (608, 'Express 2500', 'Chevrolet', 2003);
insert into car (id, model, make, year) values (609, 'E-Class', 'Mercedes-Benz', 1995);
insert into car (id, model, make, year) values (610, 'Prius', 'Toyota', 2004);
insert into car (id, model, make, year) values (611, 'Viper', 'Dodge', 2003);
insert into car (id, model, make, year) values (612, 'Econoline E250', 'Ford', 2000);
insert into car (id, model, make, year) values (613, 'GTO', 'Mitsubishi', 1998);
insert into car (id, model, make, year) values (614, 'Ram 2500', 'Dodge', 2003);
insert into car (id, model, make, year) values (615, 'B2000', 'Mazda', 1985);
insert into car (id, model, make, year) values (616, 'Coupe GT', 'Audi', 1987);
insert into car (id, model, make, year) values (617, 'LS Hybrid', 'Lexus', 2012);
insert into car (id, model, make, year) values (618, 'Crown Victoria', 'Ford', 1998);
insert into car (id, model, make, year) values (619, 'Legacy', 'Subaru', 1996);
insert into car (id, model, make, year) values (620, 'Grand Cherokee', 'Jeep', 2001);
insert into car (id, model, make, year) values (621, 'Explorer Sport Trac', 'Ford', 2001);
insert into car (id, model, make, year) values (622, 'Aerostar', 'Ford', 1996);
insert into car (id, model, make, year) values (623, 'Sonata', 'Hyundai', 2012);
insert into car (id, model, make, year) values (624, '9-3', 'Saab', 2008);
insert into car (id, model, make, year) values (625, 'Grand Prix', 'Pontiac', 1979);
insert into car (id, model, make, year) values (626, 'Voyager', 'Plymouth', 1993);
insert into car (id, model, make, year) values (627, 'Rabbit', 'Volkswagen', 2009);
insert into car (id, model, make, year) values (628, 'L-Series', 'Saturn', 2004);
insert into car (id, model, make, year) values (629, 'ES', 'Lexus', 2008);
insert into car (id, model, make, year) values (630, 'Grand Prix', 'Pontiac', 1963);
insert into car (id, model, make, year) values (631, 'Highlander', 'Toyota', 2005);
insert into car (id, model, make, year) values (632, 'F150', 'Ford', 2011);
insert into car (id, model, make, year) values (633, 'TundraMax', 'Toyota', 2012);
insert into car (id, model, make, year) values (634, 'Pathfinder', 'Nissan', 2007);
insert into car (id, model, make, year) values (635, 'RL', 'Acura', 2000);
insert into car (id, model, make, year) values (636, 'Savana 2500', 'GMC', 2011);
insert into car (id, model, make, year) values (637, 'Boxster', 'Porsche', 1997);
insert into car (id, model, make, year) values (638, 'RL', 'Acura', 2009);
insert into car (id, model, make, year) values (639, 'Continental', 'Lincoln', 2000);
insert into car (id, model, make, year) values (640, 'Previa', 'Toyota', 1992);
insert into car (id, model, make, year) values (641, 'G', 'Infiniti', 2000);
insert into car (id, model, make, year) values (642, 'A4', 'Audi', 2006);
insert into car (id, model, make, year) values (643, 'E-Class', 'Mercedes-Benz', 1997);
insert into car (id, model, make, year) values (644, 'Vision', 'Eagle', 1994);
insert into car (id, model, make, year) values (645, 'Accord', 'Honda', 2003);
insert into car (id, model, make, year) values (646, 'Thunderbird', 'Ford', 1984);
insert into car (id, model, make, year) values (647, 'Mazda6 5-Door', 'Mazda', 2006);
insert into car (id, model, make, year) values (648, 'Titan', 'Nissan', 2011);
insert into car (id, model, make, year) values (649, 'S80', 'Volvo', 2001);
insert into car (id, model, make, year) values (650, 'Accord', 'Honda', 2001);
insert into car (id, model, make, year) values (651, 'Veracruz', 'Hyundai', 2007);
insert into car (id, model, make, year) values (652, 'TT', 'Audi', 2010);
insert into car (id, model, make, year) values (653, 'LTD Crown Victoria', 'Ford', 1985);
insert into car (id, model, make, year) values (654, 'Safari', 'GMC', 1998);
insert into car (id, model, make, year) values (655, 'LaCrosse', 'Buick', 2005);
insert into car (id, model, make, year) values (656, 'MX-5', 'Mazda', 2005);
insert into car (id, model, make, year) values (657, 'Silverado 2500', 'Chevrolet', 2002);
insert into car (id, model, make, year) values (658, '924', 'Porsche', 1988);
insert into car (id, model, make, year) values (659, 'Altima', 'Nissan', 2005);
insert into car (id, model, make, year) values (660, 'Ram Van 2500', 'Dodge', 1999);
insert into car (id, model, make, year) values (661, 'S-Class', 'Mercedes-Benz', 1985);
insert into car (id, model, make, year) values (662, 'Coachbuilder', 'Buick', 1995);
insert into car (id, model, make, year) values (663, 'Swift', 'Suzuki', 1992);
insert into car (id, model, make, year) values (664, 'S4', 'Audi', 2007);
insert into car (id, model, make, year) values (665, 'Swift', 'Suzuki', 1993);
insert into car (id, model, make, year) values (666, 'Aries', 'Dodge', 1981);
insert into car (id, model, make, year) values (667, 'Stratus', 'Dodge', 2003);
insert into car (id, model, make, year) values (668, 'MX-3', 'Mazda', 1996);
insert into car (id, model, make, year) values (669, 'Relay', 'Saturn', 2006);
insert into car (id, model, make, year) values (670, 'Sedona', 'Kia', 2004);
insert into car (id, model, make, year) values (671, 'Truck', 'Mitsubishi', 1989);
insert into car (id, model, make, year) values (672, 'Murano', 'Nissan', 2006);
insert into car (id, model, make, year) values (673, '600SEL', 'Mercedes-Benz', 1993);
insert into car (id, model, make, year) values (674, 'V40', 'Volvo', 2000);
insert into car (id, model, make, year) values (675, 'Tribeca', 'Subaru', 2006);
insert into car (id, model, make, year) values (676, 'RAV4', 'Toyota', 2009);
insert into car (id, model, make, year) values (677, '350Z', 'Nissan', 2006);
insert into car (id, model, make, year) values (678, 'Prizm', 'Geo', 1992);
insert into car (id, model, make, year) values (679, 'XLR', 'Cadillac', 2005);
insert into car (id, model, make, year) values (680, 'GX', 'Lexus', 2007);
insert into car (id, model, make, year) values (681, 'Express 1500', 'Chevrolet', 1998);
insert into car (id, model, make, year) values (682, '911', 'Porsche', 1986);
insert into car (id, model, make, year) values (683, 'Ciera', 'Oldsmobile', 1994);
insert into car (id, model, make, year) values (684, 'Sonata', 'Hyundai', 2000);
insert into car (id, model, make, year) values (685, 'Riviera', 'Buick', 1986);
insert into car (id, model, make, year) values (686, 'B-Series', 'Mazda', 2004);
insert into car (id, model, make, year) values (687, 'Mazdaspeed 3', 'Mazda', 2008);
insert into car (id, model, make, year) values (688, 'Probe', 'Ford', 1997);
insert into car (id, model, make, year) values (689, 'Pajero', 'Mitsubishi', 1993);
insert into car (id, model, make, year) values (690, 'Intrepid', 'Dodge', 1999);
insert into car (id, model, make, year) values (691, 'Rondo', 'Kia', 2007);
insert into car (id, model, make, year) values (692, 'Golf', 'Volkswagen', 1987);
insert into car (id, model, make, year) values (693, 'Tracker', 'Geo', 1996);
insert into car (id, model, make, year) values (694, 'XG350', 'Hyundai', 2004);
insert into car (id, model, make, year) values (695, 'Daewoo Lacetti', 'Suzuki', 2005);
insert into car (id, model, make, year) values (696, 'Grand Marquis', 'Mercury', 1999);
insert into car (id, model, make, year) values (697, 'Celica', 'Toyota', 1976);
insert into car (id, model, make, year) values (698, 'F450', 'Ford', 2011);
insert into car (id, model, make, year) values (699, 'Ranger', 'Ford', 1991);
insert into car (id, model, make, year) values (700, 'Tundra', 'Mitsubishi', 2009);
insert into car (id, model, make, year) values (701, 'Accord', 'Honda', 1989);
insert into car (id, model, make, year) values (702, 'Pathfinder', 'Nissan', 1993);
insert into car (id, model, make, year) values (703, 'MPV', 'Mazda', 1997);
insert into car (id, model, make, year) values (704, 'Sedona', 'Kia', 2008);
insert into car (id, model, make, year) values (705, 'Pajero', 'Mitsubishi', 2004);
insert into car (id, model, make, year) values (706, 'Regal', 'Buick', 2001);
insert into car (id, model, make, year) values (707, 'PT Cruiser', 'Chrysler', 2001);
insert into car (id, model, make, year) values (708, '3 Series', 'BMW', 2003);
insert into car (id, model, make, year) values (709, 'Scoupe', 'Hyundai', 1995);
insert into car (id, model, make, year) values (710, 'VUE', 'Saturn', 2008);
insert into car (id, model, make, year) values (711, 'Civic', 'Honda', 2012);
insert into car (id, model, make, year) values (712, 'Bronco', 'Ford', 1994);
insert into car (id, model, make, year) values (713, 'Suburban 2500', 'Chevrolet', 1993);
insert into car (id, model, make, year) values (714, 'SJ', 'Suzuki', 1994);
insert into car (id, model, make, year) values (715, 'Viper', 'Dodge', 1995);
insert into car (id, model, make, year) values (716, 'Town Car', 'Lincoln', 2007);
insert into car (id, model, make, year) values (717, 'F150', 'Ford', 2004);
insert into car (id, model, make, year) values (718, 'MX-3', 'Mazda', 1994);
insert into car (id, model, make, year) values (719, 'Amigo', 'Isuzu', 1998);
insert into car (id, model, make, year) values (720, 'Starion', 'Mitsubishi', 1989);
insert into car (id, model, make, year) values (721, 'XK', 'Jaguar', 2009);
insert into car (id, model, make, year) values (722, 'Titan', 'Nissan', 2004);
insert into car (id, model, make, year) values (723, 'Sky', 'Saturn', 2007);
insert into car (id, model, make, year) values (724, 'Tiburon', 'Hyundai', 2008);
insert into car (id, model, make, year) values (725, '88', 'Oldsmobile', 1998);
insert into car (id, model, make, year) values (726, 'M', 'BMW', 2002);
insert into car (id, model, make, year) values (727, 'Precis', 'Mitsubishi', 1993);
insert into car (id, model, make, year) values (728, 'Sportage', 'Kia', 1999);
insert into car (id, model, make, year) values (729, 'F-Series', 'Ford', 2011);
insert into car (id, model, make, year) values (730, 'Integra', 'Acura', 1995);
insert into car (id, model, make, year) values (731, '3500', 'GMC', 1994);
insert into car (id, model, make, year) values (732, 'Fiesta', 'Ford', 2012);
insert into car (id, model, make, year) values (733, 'Outback', 'Subaru', 2001);
insert into car (id, model, make, year) values (734, 'Venza', 'Toyota', 2012);
insert into car (id, model, make, year) values (735, 'Liberty', 'Jeep', 2012);
insert into car (id, model, make, year) values (736, 'M', 'Infiniti', 2010);
insert into car (id, model, make, year) values (737, 'Diablo', 'Lamborghini', 1994);
insert into car (id, model, make, year) values (738, 'Sable', 'Mercury', 2004);
insert into car (id, model, make, year) values (739, 'XC60', 'Volvo', 2009);
insert into car (id, model, make, year) values (740, 'Integra', 'Acura', 1993);
insert into car (id, model, make, year) values (741, 'Prizm', 'Geo', 1994);
insert into car (id, model, make, year) values (742, 'Range Rover Sport', 'Land Rover', 2008);
insert into car (id, model, make, year) values (743, 'A8', 'Audi', 2000);
insert into car (id, model, make, year) values (744, 'Edge', 'Ford', 2008);
insert into car (id, model, make, year) values (745, 'Neon', 'Dodge', 2002);
insert into car (id, model, make, year) values (746, 'Fortwo', 'Smart', 2011);
insert into car (id, model, make, year) values (747, 'Diamante', 'Mitsubishi', 1993);
insert into car (id, model, make, year) values (748, 'Century', 'Buick', 1992);
insert into car (id, model, make, year) values (749, 'Navigator', 'Lincoln', 2011);
insert into car (id, model, make, year) values (750, 'GTI', 'Volkswagen', 2003);
insert into car (id, model, make, year) values (751, 'Ram Van 2500', 'Dodge', 2002);
insert into car (id, model, make, year) values (752, 'CLK-Class', 'Mercedes-Benz', 2008);
insert into car (id, model, make, year) values (753, 'Seville', 'Cadillac', 2004);
insert into car (id, model, make, year) values (754, 'Tacoma', 'Toyota', 2006);
insert into car (id, model, make, year) values (755, 'Firebird', 'Pontiac', 2001);
insert into car (id, model, make, year) values (756, '9000', 'Saab', 1986);
insert into car (id, model, make, year) values (757, 'L300', 'Mitsubishi', 1989);
insert into car (id, model, make, year) values (758, 'Fillmore', 'Fillmore', 1960);
insert into car (id, model, make, year) values (759, 'VehiCROSS', 'Isuzu', 2001);
insert into car (id, model, make, year) values (760, 'Prius Plug-in', 'Toyota', 2012);
insert into car (id, model, make, year) values (761, 'R8', 'Audi', 2012);
insert into car (id, model, make, year) values (762, 'Yukon Denali', 'GMC', 2006);
insert into car (id, model, make, year) values (763, 'Passport', 'Honda', 1997);
insert into car (id, model, make, year) values (764, 'Mark LT', 'Lincoln', 2006);
insert into car (id, model, make, year) values (765, 'G', 'Infiniti', 2010);
insert into car (id, model, make, year) values (766, 'Elantra', 'Hyundai', 1998);
insert into car (id, model, make, year) values (767, 'Legend', 'Acura', 1988);
insert into car (id, model, make, year) values (768, 'LR2', 'Land Rover', 2011);
insert into car (id, model, make, year) values (769, 'Trans Sport', 'Pontiac', 1999);
insert into car (id, model, make, year) values (770, 'Aurora', 'Oldsmobile', 1996);
insert into car (id, model, make, year) values (771, 'GL-Class', 'Mercedes-Benz', 2012);
insert into car (id, model, make, year) values (772, 'Azera', 'Hyundai', 2009);
insert into car (id, model, make, year) values (773, 'E250', 'Ford', 1984);
insert into car (id, model, make, year) values (774, 'S2000', 'Honda', 2003);
insert into car (id, model, make, year) values (775, 'G37', 'Infiniti', 2011);
insert into car (id, model, make, year) values (776, 'Scirocco', 'Volkswagen', 1984);
insert into car (id, model, make, year) values (777, 'Esteem', 'Suzuki', 1996);
insert into car (id, model, make, year) values (778, 'Swift', 'Suzuki', 1987);
insert into car (id, model, make, year) values (779, 'Durango', 'Dodge', 2005);
insert into car (id, model, make, year) values (780, 'ES', 'Lexus', 2006);
insert into car (id, model, make, year) values (781, 'Insight', 'Honda', 2002);
insert into car (id, model, make, year) values (782, 'Rondo', 'Kia', 2007);
insert into car (id, model, make, year) values (783, 'Venza', 'Toyota', 2009);
insert into car (id, model, make, year) values (784, 'RDX', 'Acura', 2010);
insert into car (id, model, make, year) values (785, 'E150', 'Ford', 2007);
insert into car (id, model, make, year) values (786, 'Accord', 'Honda', 1988);
insert into car (id, model, make, year) values (787, 'Outback', 'Subaru', 2000);
insert into car (id, model, make, year) values (788, 'S-Class', 'Mercedes-Benz', 1995);
insert into car (id, model, make, year) values (789, 'GS', 'Lexus', 1999);
insert into car (id, model, make, year) values (790, 'Equinox', 'Chevrolet', 2012);
insert into car (id, model, make, year) values (791, 'Previa', 'Toyota', 1997);
insert into car (id, model, make, year) values (792, 'Neon', 'Plymouth', 1997);
insert into car (id, model, make, year) values (793, 'Camry', 'Toyota', 2002);
insert into car (id, model, make, year) values (794, '3 Series', 'BMW', 1994);
insert into car (id, model, make, year) values (795, 'Express 1500', 'Chevrolet', 2010);
insert into car (id, model, make, year) values (796, 'Cherokee', 'Jeep', 1996);
insert into car (id, model, make, year) values (797, 'XJ', 'Jaguar', 2012);
insert into car (id, model, make, year) values (798, 'Lanos', 'Daewoo', 2001);
insert into car (id, model, make, year) values (799, 'Outlook', 'Saturn', 2008);
insert into car (id, model, make, year) values (800, 'Pacifica', 'Chrysler', 2008);
insert into car (id, model, make, year) values (801, '1 Series', 'BMW', 2011);
insert into car (id, model, make, year) values (802, 'X-Type', 'Jaguar', 2003);
insert into car (id, model, make, year) values (803, 'Accent', 'Hyundai', 2008);
insert into car (id, model, make, year) values (804, 'Fit', 'Honda', 2007);
insert into car (id, model, make, year) values (805, 'Accent', 'Hyundai', 1999);
insert into car (id, model, make, year) values (806, 'Sonata', 'Hyundai', 2000);
insert into car (id, model, make, year) values (807, 'MX-6', 'Mazda', 1993);
insert into car (id, model, make, year) values (808, 'Express 1500', 'Chevrolet', 2000);
insert into car (id, model, make, year) values (809, 'Patriot', 'Jeep', 2010);
insert into car (id, model, make, year) values (810, 'Park Avenue', 'Buick', 2001);
insert into car (id, model, make, year) values (811, 'Regency', 'Oldsmobile', 1997);
insert into car (id, model, make, year) values (812, 'Savana 1500', 'GMC', 2007);
insert into car (id, model, make, year) values (813, 'Colt Vista', 'Plymouth', 1992);
insert into car (id, model, make, year) values (814, 'Miata MX-5', 'Mazda', 1995);
insert into car (id, model, make, year) values (815, 'LaCrosse', 'Buick', 2009);
insert into car (id, model, make, year) values (816, 'Silhouette', 'Oldsmobile', 1992);
insert into car (id, model, make, year) values (817, 'Impreza', 'Subaru', 2002);
insert into car (id, model, make, year) values (818, 'Discovery', 'Land Rover', 2001);
insert into car (id, model, make, year) values (819, 'Acadia', 'GMC', 2007);
insert into car (id, model, make, year) values (820, 'Esteem', 'Suzuki', 1996);
insert into car (id, model, make, year) values (821, 'G-Series 3500', 'Chevrolet', 1998);
insert into car (id, model, make, year) values (822, 'Impala', 'Chevrolet', 2004);
insert into car (id, model, make, year) values (823, 'GLI', 'Volkswagen', 2008);
insert into car (id, model, make, year) values (824, 'TL', 'Acura', 1997);
insert into car (id, model, make, year) values (825, 'SSR', 'Chevrolet', 2006);
insert into car (id, model, make, year) values (826, 'XK Series', 'Jaguar', 2004);
insert into car (id, model, make, year) values (827, 'Eurovan', 'Volkswagen', 2000);
insert into car (id, model, make, year) values (828, 'Sequoia', 'Toyota', 2011);
insert into car (id, model, make, year) values (829, 'Envoy XUV', 'GMC', 2005);
insert into car (id, model, make, year) values (830, 'W201', 'Mercedes-Benz', 1993);
insert into car (id, model, make, year) values (831, 'SC', 'Lexus', 2000);
insert into car (id, model, make, year) values (832, 'F250', 'Ford', 2008);
insert into car (id, model, make, year) values (833, '323', 'Mazda', 1992);
insert into car (id, model, make, year) values (834, 'Rapide', 'Aston Martin', 2012);
insert into car (id, model, make, year) values (835, 'Suburban 2500', 'Chevrolet', 1996);
insert into car (id, model, make, year) values (836, 'MKT', 'Lincoln', 2012);
insert into car (id, model, make, year) values (837, 'F350', 'Ford', 2009);
insert into car (id, model, make, year) values (838, 'Avenger', 'Dodge', 1996);
insert into car (id, model, make, year) values (839, 'CC', 'Volkswagen', 2013);
insert into car (id, model, make, year) values (840, 'LS', 'Lincoln', 2000);
insert into car (id, model, make, year) values (841, 'Q', 'Infiniti', 2006);
insert into car (id, model, make, year) values (842, 'Galant', 'Mitsubishi', 2011);
insert into car (id, model, make, year) values (843, 'Solara', 'Toyota', 2002);
insert into car (id, model, make, year) values (844, 'Mazda6', 'Mazda', 2006);
insert into car (id, model, make, year) values (845, 'RAV4', 'Toyota', 2006);
insert into car (id, model, make, year) values (846, 'M-Class', 'Mercedes-Benz', 1999);
insert into car (id, model, make, year) values (847, 'Miata MX-5', 'Mazda', 2004);
insert into car (id, model, make, year) values (848, 'Tracker', 'Chevrolet', 1998);
insert into car (id, model, make, year) values (849, 'Ram 3500', 'Dodge', 2005);
insert into car (id, model, make, year) values (850, 'XLR', 'Cadillac', 2007);
insert into car (id, model, make, year) values (851, 'E-Class', 'Mercedes-Benz', 1994);
insert into car (id, model, make, year) values (852, 'A8', 'Audi', 2004);
insert into car (id, model, make, year) values (853, 'Solara', 'Toyota', 2004);
insert into car (id, model, make, year) values (854, 'GranTurismo', 'Maserati', 2011);
insert into car (id, model, make, year) values (855, 'Camry Hybrid', 'Toyota', 2009);
insert into car (id, model, make, year) values (856, 'Z3', 'BMW', 1996);
insert into car (id, model, make, year) values (857, 'Sedona', 'Kia', 2011);
insert into car (id, model, make, year) values (858, 'xA', 'Scion', 2004);
insert into car (id, model, make, year) values (859, 'Riviera', 'Buick', 1989);
insert into car (id, model, make, year) values (860, '57', 'Maybach', 2004);
insert into car (id, model, make, year) values (861, 'Suburban 2500', 'Chevrolet', 1994);
insert into car (id, model, make, year) values (862, 'GT-R', 'Nissan', 2013);
insert into car (id, model, make, year) values (863, 'Liberty', 'Jeep', 2012);
insert into car (id, model, make, year) values (864, 'Prizm', 'Geo', 1992);
insert into car (id, model, make, year) values (865, '1500', 'Chevrolet', 1999);
insert into car (id, model, make, year) values (866, 'Corvette', 'Chevrolet', 2000);
insert into car (id, model, make, year) values (867, 'Familia', 'Mazda', 1990);
insert into car (id, model, make, year) values (868, 'Santa Fe', 'Hyundai', 2001);
insert into car (id, model, make, year) values (869, '3500', 'GMC', 1993);
insert into car (id, model, make, year) values (870, 'Festiva', 'Ford', 1990);
insert into car (id, model, make, year) values (871, 'Xterra', 'Nissan', 2008);
insert into car (id, model, make, year) values (872, 'XLR-V', 'Cadillac', 2007);
insert into car (id, model, make, year) values (873, 'F250', 'Ford', 2002);
insert into car (id, model, make, year) values (874, 'Passat', 'Volkswagen', 2006);
insert into car (id, model, make, year) values (875, 'Escalade', 'Cadillac', 2006);
insert into car (id, model, make, year) values (876, 'Cutlass', 'Oldsmobile', 1997);
insert into car (id, model, make, year) values (877, 'S80', 'Volvo', 2012);
insert into car (id, model, make, year) values (878, 'GranTurismo', 'Maserati', 2011);
insert into car (id, model, make, year) values (879, 'Z3', 'BMW', 1996);
insert into car (id, model, make, year) values (880, 'Mountaineer', 'Mercury', 2006);
insert into car (id, model, make, year) values (881, 'Coupe Quattro', 'Audi', 1991);
insert into car (id, model, make, year) values (882, 'QX', 'Infiniti', 2002);
insert into car (id, model, make, year) values (883, 'Neon', 'Dodge', 1995);
insert into car (id, model, make, year) values (884, '6 Series', 'BMW', 2005);
insert into car (id, model, make, year) values (885, '928', 'Porsche', 1993);
insert into car (id, model, make, year) values (886, 'F250', 'Ford', 1984);
insert into car (id, model, make, year) values (887, 'XC60', 'Volvo', 2010);
insert into car (id, model, make, year) values (888, 'F-Series', 'Ford', 2004);
insert into car (id, model, make, year) values (889, 'STS-V', 'Cadillac', 2009);
insert into car (id, model, make, year) values (890, 'Tredia', 'Mitsubishi', 1985);
insert into car (id, model, make, year) values (891, 'Chariot', 'Mitsubishi', 1986);
insert into car (id, model, make, year) values (892, 'Expedition', 'Ford', 2012);
insert into car (id, model, make, year) values (893, 'Raider', 'Mitsubishi', 2006);
insert into car (id, model, make, year) values (894, 'Sorento', 'Kia', 2011);
insert into car (id, model, make, year) values (895, 'XC60', 'Volvo', 2011);
insert into car (id, model, make, year) values (896, 'X5', 'BMW', 2003);
insert into car (id, model, make, year) values (897, 'LX', 'Lexus', 1997);
insert into car (id, model, make, year) values (898, 'Passat', 'Volkswagen', 1987);
insert into car (id, model, make, year) values (899, 'Corvette', 'Chevrolet', 1993);
insert into car (id, model, make, year) values (900, '88', 'Oldsmobile', 1997);
insert into car (id, model, make, year) values (901, 'Continental Super', 'Bentley', 2011);
insert into car (id, model, make, year) values (902, '626', 'Mazda', 2000);
insert into car (id, model, make, year) values (903, 'Daewoo Magnus', 'Suzuki', 2006);
insert into car (id, model, make, year) values (904, 'Versa', 'Nissan', 2010);
insert into car (id, model, make, year) values (905, 'Tahoe', 'Chevrolet', 2008);
insert into car (id, model, make, year) values (906, 'Monte Carlo', 'Chevrolet', 2000);
insert into car (id, model, make, year) values (907, '3 Series', 'BMW', 1993);
insert into car (id, model, make, year) values (908, 'Cutlass Supreme', 'Oldsmobile', 1997);
insert into car (id, model, make, year) values (909, 'Swift', 'Suzuki', 1992);
insert into car (id, model, make, year) values (910, 'SLX', 'Acura', 1999);
insert into car (id, model, make, year) values (911, 'Savana 1500', 'GMC', 2000);
insert into car (id, model, make, year) values (912, 'E150', 'Ford', 2003);
insert into car (id, model, make, year) values (913, 'S-Series', 'Saturn', 1995);
insert into car (id, model, make, year) values (914, 'Grand Prix', 'Pontiac', 1971);
insert into car (id, model, make, year) values (915, 'Celica', 'Toyota', 1993);
insert into car (id, model, make, year) values (916, 'Tiguan', 'Volkswagen', 2009);
insert into car (id, model, make, year) values (917, 'Altima', 'Nissan', 2013);
insert into car (id, model, make, year) values (918, 'Odyssey', 'Honda', 2011);
insert into car (id, model, make, year) values (919, 'Firefly', 'Pontiac', 1987);
insert into car (id, model, make, year) values (920, 'Yukon XL 2500', 'GMC', 2002);
insert into car (id, model, make, year) values (921, 'Prizm', 'Geo', 1996);
insert into car (id, model, make, year) values (922, 'Windstar', 'Ford', 1995);
insert into car (id, model, make, year) values (923, 'EXP', 'Ford', 1988);
insert into car (id, model, make, year) values (924, 'C-Class', 'Mercedes-Benz', 2006);
insert into car (id, model, make, year) values (925, 'Esperante', 'Panoz', 2006);
insert into car (id, model, make, year) values (926, 'Firebird', 'Pontiac', 1985);
insert into car (id, model, make, year) values (927, 'Silhouette', 'Oldsmobile', 1996);
insert into car (id, model, make, year) values (928, '3500', 'Chevrolet', 1994);
insert into car (id, model, make, year) values (929, 'Phaeton', 'Volkswagen', 2005);
insert into car (id, model, make, year) values (930, 'Crossfire Roadster', 'Chrysler', 2006);
insert into car (id, model, make, year) values (931, '9-3', 'Saab', 2000);
insert into car (id, model, make, year) values (932, 'Windstar', 'Ford', 1995);
insert into car (id, model, make, year) values (933, 'Avalon', 'Toyota', 2011);
insert into car (id, model, make, year) values (934, 'Jetta', 'Volkswagen', 2001);
insert into car (id, model, make, year) values (935, 'Silverado', 'Chevrolet', 2010);
insert into car (id, model, make, year) values (936, 'Loyale', 'Subaru', 1990);
insert into car (id, model, make, year) values (937, 'VUE', 'Saturn', 2010);
insert into car (id, model, make, year) values (938, 'Avalanche', 'Chevrolet', 2007);
insert into car (id, model, make, year) values (939, 'Pajero', 'Mitsubishi', 1997);
insert into car (id, model, make, year) values (940, '6 Series', 'BMW', 2012);
insert into car (id, model, make, year) values (941, 'Corolla', 'Toyota', 2009);
insert into car (id, model, make, year) values (942, 'F450', 'Ford', 2011);
insert into car (id, model, make, year) values (943, 'Passat', 'Volkswagen', 1987);
insert into car (id, model, make, year) values (944, 'Cutlass Supreme', 'Oldsmobile', 1997);
insert into car (id, model, make, year) values (945, 'Grand Marquis', 'Mercury', 1988);
insert into car (id, model, make, year) values (946, 'Safari', 'GMC', 1998);
insert into car (id, model, make, year) values (947, 'Vibe', 'Pontiac', 2008);
insert into car (id, model, make, year) values (948, 'TL', 'Acura', 2002);
insert into car (id, model, make, year) values (949, 'iQ', 'Scion', 2012);
insert into car (id, model, make, year) values (950, 'F430 Spider', 'Ferrari', 2006);
insert into car (id, model, make, year) values (951, 'Justy', 'Subaru', 1990);
insert into car (id, model, make, year) values (952, 'Suburban 1500', 'Chevrolet', 1997);
insert into car (id, model, make, year) values (953, 'New Yorker', 'Chrysler', 1994);
insert into car (id, model, make, year) values (954, 'Grand Am', 'Pontiac', 1987);
insert into car (id, model, make, year) values (955, '1 Series', 'BMW', 2010);
insert into car (id, model, make, year) values (956, 'Murano', 'Nissan', 2004);
insert into car (id, model, make, year) values (957, 'Justy', 'Subaru', 1990);
insert into car (id, model, make, year) values (958, 'Galaxie', 'Ford', 1966);
insert into car (id, model, make, year) values (959, 'LX', 'Lexus', 2013);
insert into car (id, model, make, year) values (960, 'Rodeo', 'Isuzu', 1995);
insert into car (id, model, make, year) values (961, '3500', 'Chevrolet', 1996);
insert into car (id, model, make, year) values (962, '2500', 'Chevrolet', 1995);
insert into car (id, model, make, year) values (963, 'E-Class', 'Mercedes-Benz', 2012);
insert into car (id, model, make, year) values (964, 'Maxima', 'Nissan', 2010);
insert into car (id, model, make, year) values (965, 'A4', 'Audi', 2009);
insert into car (id, model, make, year) values (966, 'Panamera', 'Porsche', 2012);
insert into car (id, model, make, year) values (967, 'CTS', 'Cadillac', 2007);
insert into car (id, model, make, year) values (968, 'Celica', 'Toyota', 1992);
insert into car (id, model, make, year) values (969, '530', 'BMW', 2006);
insert into car (id, model, make, year) values (970, 'LeMans', 'Pontiac', 1968);
insert into car (id, model, make, year) values (971, 'E350', 'Ford', 2003);
insert into car (id, model, make, year) values (972, 'Echo', 'Toyota', 2003);
insert into car (id, model, make, year) values (973, 'Ram 3500 Club', 'Dodge', 1995);
insert into car (id, model, make, year) values (974, 'Town & Country', 'Chrysler', 2009);
insert into car (id, model, make, year) values (975, 'F350', 'Ford', 2002);
insert into car (id, model, make, year) values (976, 'Century', 'Buick', 1986);
insert into car (id, model, make, year) values (977, 'Diamante', 'Mitsubishi', 1996);
insert into car (id, model, make, year) values (978, 'Tercel', 'Toyota', 1996);
insert into car (id, model, make, year) values (979, 'Ranger', 'Ford', 1990);
insert into car (id, model, make, year) values (980, 'Challenger', 'Mitsubishi', 2000);
insert into car (id, model, make, year) values (981, 'Golf', 'Volkswagen', 1987);
insert into car (id, model, make, year) values (982, 'C70', 'Volvo', 2013);
insert into car (id, model, make, year) values (983, 'F430', 'Ferrari', 2009);
insert into car (id, model, make, year) values (984, 'S-Class', 'Mercedes-Benz', 2006);
insert into car (id, model, make, year) values (985, 'Escalade ESV', 'Cadillac', 2005);
insert into car (id, model, make, year) values (986, 'Bronco II', 'Ford', 1984);
insert into car (id, model, make, year) values (987, 'Tempo', 'Ford', 1988);
insert into car (id, model, make, year) values (988, '900', 'Saab', 1984);
insert into car (id, model, make, year) values (989, '100', 'Audi', 1991);
insert into car (id, model, make, year) values (990, 'Sierra 1500', 'GMC', 2005);
insert into car (id, model, make, year) values (991, 'LeMans', 'Pontiac', 1967);
insert into car (id, model, make, year) values (992, 'New Yorker', 'Chrysler', 1993);
insert into car (id, model, make, year) values (993, 'Sienna', 'Toyota', 2009);
insert into car (id, model, make, year) values (994, 'LX', 'Lexus', 2003);
insert into car (id, model, make, year) values (995, 'Camaro', 'Chevrolet', 2002);
insert into car (id, model, make, year) values (996, 'M5', 'BMW', 1992);
insert into car (id, model, make, year) values (997, 'Achieva', 'Oldsmobile', 1995);
insert into car (id, model, make, year) values (998, 'Tundra', 'Toyota', 2010);
insert into car (id, model, make, year) values (999, 'Roadmaster', 'Buick', 1992);
insert into car (id, model, make, year) values (1000, 'Cougar', 'Mercury', 1989);
