// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.2
// source: crud_proto/crud_proto.proto

package crud_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Car struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Model string `protobuf:"bytes,1,opt,name=Model,proto3" json:"Model,omitempty"`
	Make  string `protobuf:"bytes,2,opt,name=Make,proto3" json:"Make,omitempty"`
	Year  string `protobuf:"bytes,3,opt,name=Year,proto3" json:"Year,omitempty"`
}

func (x *Car) Reset() {
	*x = Car{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crud_proto_crud_proto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Car) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Car) ProtoMessage() {}

func (x *Car) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_crud_proto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Car.ProtoReflect.Descriptor instead.
func (*Car) Descriptor() ([]byte, []int) {
	return file_crud_proto_crud_proto_proto_rawDescGZIP(), []int{0}
}

func (x *Car) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *Car) GetMake() string {
	if x != nil {
		return x.Make
	}
	return ""
}

func (x *Car) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Carid int32 `protobuf:"varint,1,opt,name=Carid,proto3" json:"Carid,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crud_proto_crud_proto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_crud_proto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_crud_proto_crud_proto_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetCarid() int32 {
	if x != nil {
		return x.Carid
	}
	return 0
}

type CarComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Queryid  *Id  `protobuf:"bytes,1,opt,name=Queryid,proto3" json:"Queryid,omitempty"`
	Querycar *Car `protobuf:"bytes,2,opt,name=Querycar,proto3" json:"Querycar,omitempty"`
}

func (x *CarComplete) Reset() {
	*x = CarComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_crud_proto_crud_proto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarComplete) ProtoMessage() {}

func (x *CarComplete) ProtoReflect() protoreflect.Message {
	mi := &file_crud_proto_crud_proto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarComplete.ProtoReflect.Descriptor instead.
func (*CarComplete) Descriptor() ([]byte, []int) {
	return file_crud_proto_crud_proto_proto_rawDescGZIP(), []int{2}
}

func (x *CarComplete) GetQueryid() *Id {
	if x != nil {
		return x.Queryid
	}
	return nil
}

func (x *CarComplete) GetQuerycar() *Car {
	if x != nil {
		return x.Querycar
	}
	return nil
}

var File_crud_proto_crud_proto_proto protoreflect.FileDescriptor

var file_crud_proto_crud_proto_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x72, 0x75,
	0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63,
	0x72, 0x75, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x03, 0x43, 0x61, 0x72,
	0x12, 0x14, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4d, 0x61, 0x6b, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4d, 0x61, 0x6b, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x59, 0x65,
	0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x59, 0x65, 0x61, 0x72, 0x22, 0x1a,
	0x0a, 0x02, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x61, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x43, 0x61, 0x72, 0x69, 0x64, 0x22, 0x64, 0x0a, 0x0b, 0x43, 0x61,
	0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x28, 0x0a, 0x07, 0x51, 0x75, 0x65,
	0x72, 0x79, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x72, 0x75,
	0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x64, 0x52, 0x07, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x69, 0x64, 0x12, 0x2b, 0x0a, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x63, 0x61, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x52, 0x08, 0x51, 0x75, 0x65, 0x72, 0x79, 0x63, 0x61, 0x72,
	0x32, 0xd7, 0x01, 0x0a, 0x07, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x43, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x2e, 0x63, 0x72, 0x75,
	0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x75,
	0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x22, 0x00, 0x12, 0x38, 0x0a,
	0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x2e, 0x63, 0x72,
	0x75, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x43, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x61, 0x72, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x49, 0x64, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x22, 0x00, 0x12, 0x30, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0f, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x1a, 0x0f, 0x2e, 0x63, 0x72, 0x75, 0x64, 0x5f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x61, 0x72, 0x22, 0x00, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b,
	0x63, 0x72, 0x75, 0x64, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_crud_proto_crud_proto_proto_rawDescOnce sync.Once
	file_crud_proto_crud_proto_proto_rawDescData = file_crud_proto_crud_proto_proto_rawDesc
)

func file_crud_proto_crud_proto_proto_rawDescGZIP() []byte {
	file_crud_proto_crud_proto_proto_rawDescOnce.Do(func() {
		file_crud_proto_crud_proto_proto_rawDescData = protoimpl.X.CompressGZIP(file_crud_proto_crud_proto_proto_rawDescData)
	})
	return file_crud_proto_crud_proto_proto_rawDescData
}

var file_crud_proto_crud_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_crud_proto_crud_proto_proto_goTypes = []interface{}{
	(*Car)(nil),         // 0: crud_proto.Car
	(*Id)(nil),          // 1: crud_proto.Id
	(*CarComplete)(nil), // 2: crud_proto.CarComplete
}
var file_crud_proto_crud_proto_proto_depIdxs = []int32{
	1, // 0: crud_proto.CarComplete.Queryid:type_name -> crud_proto.Id
	0, // 1: crud_proto.CarComplete.Querycar:type_name -> crud_proto.Car
	1, // 2: crud_proto.CarInfo.GetCarInfo:input_type -> crud_proto.Id
	2, // 3: crud_proto.CarInfo.UpdateInfo:input_type -> crud_proto.CarComplete
	1, // 4: crud_proto.CarInfo.DeleteInfo:input_type -> crud_proto.Id
	0, // 5: crud_proto.CarInfo.CreateInfo:input_type -> crud_proto.Car
	0, // 6: crud_proto.CarInfo.GetCarInfo:output_type -> crud_proto.Car
	0, // 7: crud_proto.CarInfo.UpdateInfo:output_type -> crud_proto.Car
	0, // 8: crud_proto.CarInfo.DeleteInfo:output_type -> crud_proto.Car
	0, // 9: crud_proto.CarInfo.CreateInfo:output_type -> crud_proto.Car
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_crud_proto_crud_proto_proto_init() }
func file_crud_proto_crud_proto_proto_init() {
	if File_crud_proto_crud_proto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_crud_proto_crud_proto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Car); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_crud_proto_crud_proto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_crud_proto_crud_proto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_crud_proto_crud_proto_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crud_proto_crud_proto_proto_goTypes,
		DependencyIndexes: file_crud_proto_crud_proto_proto_depIdxs,
		MessageInfos:      file_crud_proto_crud_proto_proto_msgTypes,
	}.Build()
	File_crud_proto_crud_proto_proto = out.File
	file_crud_proto_crud_proto_proto_rawDesc = nil
	file_crud_proto_crud_proto_proto_goTypes = nil
	file_crud_proto_crud_proto_proto_depIdxs = nil
}
